### ISSUE TITLE
Jquery has to be injected in module based environments

### ISSUE THREAD

**Issue by SimonHarte** [gfdev/javascript-jquery-transport-xdr#2]
I don't know webpack so can't do a PR for this, but if you try to include this plugin in a CommonJS environment it fails because `$` is not defined.

**Comment by gfdev** [comment]
@SimonHarte thanks for the information. Could you please give more details about usage? For example piece of code where you use plugin?

**Comment by SimonHarte** [comment]
Yeah sure, we have have a grunt build with browserify and we put our project JS together by using the `import` statement, which means that every component/plugin will be handled as an independent module.

So here's how I include the plugin:
`import '../../../bower_components/jquery-transport-xdr/dist/jquery.transport.xdr.js'`

**Comment by gfdev** [comment]
@SimonHarte, could you please check your issue with version 1.0.6?

**Comment by SimonHarte** [comment]
Seems fine so far, only that the module name should be `jquery` instead of `jQuery`, as seen in for example [typeahead.js](https://github.com/twitter/typeahead.js/blob/master/dist/typeahead.jquery.js).

**Comment by gfdev** [comment]
@SimonHarte, many thanks!
