### ISSUE TITLE
data id undefined

### ISSUE THREAD

**Issue by seifeddineSymane** [gfdev/javascript-jquery-transport-xdr#3]
Hello, thanks for this plugin.
When i make an ajax call in ie9 all thinks works greatly in Network (i get all the json data) expect when i the callback is triggered the data param in success method is undefined.

``` javascript
    $.ajax({
        url: yahooQuoteLink,
        type: "POST",
        datatype: 'json',
        timeout: 8000,
        success: function (data) {
            //data is undefined and the view is not updated.
            if(data){
                updateView(widget, data);
            }

        },
        error: function () {
            $(widget).find(".loader").hide();
        }
    });
```

**Comment by gfdev** [comment]
Hi @seifeddineSymane, I'm not sure that it's connected with plugin itself, data passes to jQuery as is.
